export const MERCHANTS_GET_REQUEST = 'MERCHANTS_GET_REQUEST';
export const MERCHANTS_GET_SUCCESS = 'MERCHANTS_GET_SUCCESS';
export const MERCHANTS_GET_FAILURE = 'MERCHANTS_GET_FAILURE';
export const MERCHANTS_EDIT_REQUEST = 'MERCHANTS_EDIT_REQUEST';
export const MERCHANTS_EDIT_SUCCESS = 'MERCHANTS_EDIT_SUCCESS';
export const MERCHANTS_EDIT_FAILURE = 'MERCHANTS_EDIT_FAILURE';
export const MERCHANTS_DELETE_REQUEST = 'MERCHANTS_DELETE_REQUEST';
export const MERCHANTS_DELETE_SUCCESS = 'MERCHANTS_DELETE_SUCCESS';
export const MERCHANTS_DELETE_FAILURE = 'MERCHANTS_DELETE_FAILURE';
export const MERCHANTS_COMPLETE = 'MERCHANTS_COMPLETE';
export const MERCHANTS_UNMOUNT = 'MERCHANTS_UNMOUNT';
export const MERCHANTS_SET_MERCHANT_IN_ACTION =
  'MERCHANTS_SET_MERCHANT_IN_ACTION';
export const MERCHANTS_SHOW_NOT_USED_IN_TXNS_ONLY =
  'MERCHANTS_SHOW_NOT_USED_IN_TXNS_ONLY';
export const MERCHANTS_SET_NAME_BEGINS_WITH = 'MERCHANTS_SET_NAME_BEGINS_WITH';
export const MERCHANTS_CLEAR_FILTER = 'MERCHANTS_CLEAR_FILTER';
export const MERCHANTS_UPDATE_MODAL_ACTION = 'MERCHANTS_UPDATE_MODAL_ACTION';
export const MERCHANTS_DELETE_MODAL_ACTION = 'MERCHANTS_DELETE_MODAL_ACTION';
export const MERCHANTS_MODAL_INPUT = 'MERCHANTS_MODAL_INPUT';
export const MERCHANTS_MODAL_CLOSE = 'MERCHANTS_MODAL_CLOSE';
export const MERCHANTS_SELECT_MERCHANT = 'MERCHANTS_SELECT_MERCHANT';
export const MERCHANTS_SELECT_MERCHANT_TRANSACTIONS =
  'MERCHANTS_SELECT_MERCHANT_TRANSACTIONS';
