export const REPORT_CURRENT_BALANCES_REQUEST =
  'REPORT_CURRENT_BALANCES_REQUEST';
export const REPORT_CURRENT_BALANCES_RESPONSE =
  'REPORT_CURRENT_BALANCES_RESPONSE';
export const REPORT_CURRENT_BALANCES_SUCCESS =
  'REPORT_CURRENT_BALANCES_SUCCESS';
export const REPORT_CURRENT_BALANCES_FAILURE =
  'REPORT_CURRENT_BALANCES_FAILURE';
export const REPORT_CURRENT_BALANCES_COMPLETE =
  'REPORT_CURRENT_BALANCES_COMPLETE';
export const REPORT_CASH_FLOWS_REQUEST = 'REPORT_CASH_FLOWS_REQUEST';
export const REPORT_CASH_FLOWS_RESPONSE = 'REPORT_CASH_FLOWS_RESPONSE';
export const REPORT_CASH_FLOWS_SUCCESS = 'REPORT_CASH_FLOWS_SUCCESS';
export const REPORT_CASH_FLOWS_FAILURE = 'REPORT_CASH_FLOWS_FAILURE';
export const REPORT_CASH_FLOWS_COMPLETE = 'REPORT_CASH_FLOWS_COMPLETE';
export const REPORT_CATEGORY_TYPES_REQUEST = 'REPORT_CATEGORY_TYPES_REQUEST';
export const REPORT_CATEGORY_TYPES_RESPONSE = 'REPORT_CATEGORY_TYPES_RESPONSE';
export const REPORT_CATEGORY_TYPES_SUCCESS = 'REPORT_CATEGORY_TYPES_SUCCESS';
export const REPORT_CATEGORY_TYPES_FAILURE = 'REPORT_CATEGORY_TYPES_FAILURE';
export const REPORT_CATEGORY_TYPES_COMPLETE = 'REPORT_CATEGORY_TYPES_COMPLETE';
