export const TRANSACTIONS_GET_REQUEST = 'TRANSACTIONS_GET_REQUEST';
export const TRANSACTIONS_GET_SUCCESS = 'TRANSACTIONS_GET_SUCCESS';
export const TRANSACTIONS_GET_FAILURE = 'TRANSACTIONS_GET_FAILURE';
export const TRANSACTIONS_EDIT_REQUEST = 'TRANSACTIONS_EDIT_REQUEST';
export const TRANSACTIONS_EDIT_SUCCESS = 'TRANSACTIONS_EDIT_SUCCESS';
export const TRANSACTIONS_EDIT_FAILURE = 'TRANSACTIONS_EDIT_FAILURE';
export const TRANSACTIONS_DELETE_REQUEST = 'TRANSACTIONS_DELETE_REQUEST';
export const TRANSACTIONS_DELETE_SUCCESS = 'TRANSACTIONS_DELETE_SUCCESS';
export const TRANSACTIONS_DELETE_FAILURE = 'TRANSACTIONS_DELETE_FAILURE';
export const TRANSACTIONS_COMPLETE = 'TRANSACTIONS_COMPLETE';
export const TRANSACTIONS_UNMOUNT = 'TRANSACTIONS_UNMOUNT';
export const TRANSACTIONS_SELECT_TRANSACTION =
  'TRANSACTIONS_SELECT_TRANSACTION';
export const TRANSACTIONS_SET_FILTER = 'TRANSACTIONS_SET_FILTER';
export const TRANSACTIONS_SET_FILTERS = 'TRANSACTIONS_SET_FILTERS';
export const TRANSACTIONS_RESET_FILTERS = 'TRANSACTIONS_RESET_FILTERS';
