// REF TYPES
export const REF_TYPES_REQUEST = 'REF_TYPES_REQUEST';
export const REF_TYPES_SUCCESS = 'REF_TYPES_SUCCESS';
export const REF_TYPES_FAILURE = 'REF_TYPES_FAILURE';
export const REF_TYPES_COMPLETE = 'REF_TYPES_COMPLETE';

// ALERT
export const SET_ALERT = 'SET_ALERT';
export const RESET_ALERT = 'RESET_ALERT';

// SPINNER
export const SET_SPINNER = 'SET_SPINNER';
export const RESET_SPINNER = 'RESET_SPINNER';

// PREFETCH
export const PREFETCH_DISPATCH_ACTION = 'PREFETCH_DISPATCH_ACTION';
