name: NodeJS with Webpack

on:
  push:
    branches: [ main, petsuispa ]
  pull_request:
    branches: [ main, petsuispa ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Prod Check
        run: npx webpack --config webpack.prod.config.js
